// SKELETON
export const GET_SKELETON = 'GET_SKELETON';
export const GET_SKELETONS = 'GET_SKELETONS';
export const GET_ALL_SKELETONS = 'GET_ALL_SKELETONS';
export const SKELETON_ERROR = 'SKELETON_ERROR';
export const CREATE_SKELETON = 'CREATE_SKELETON';
export const UPDATE_SKELETON = 'UPDATE_SKELETON';
export const REMOVE_SKELETON = 'REMOVE_SKELETON';
