// MEDIA_OBJECT
export const GET_MEDIA_OBJECT = 'GET_MEDIA_OBJECT';
export const GET_MEDIA_OBJECTS = 'GET_MEDIA_OBJECTS';
export const GET_ALL_MEDIA_OBJECTS = 'GET_ALL_MEDIA_OBJECTS';
export const MEDIA_OBJECT_ERROR = 'MEDIA_OBJECT_ERROR';
export const CREATE_MEDIA_OBJECT = 'CREATE_MEDIA_OBJECT';
export const UPDATE_MEDIA_OBJECT = 'UPDATE_MEDIA_OBJECT';
export const REMOVE_MEDIA_OBJECT = 'REMOVE_MEDIA_OBJECT';
